# for training
pretrain: ./config/efficientnet.pth

# url or local path (predict)
weights: ./config/efficientnet.pth

backbone: efficientnet_b7
cnn:
    pretrained: True
    # pooling stride size
    ss:
        - [2, 2]
        - [2, 2]
        - [2, 1]
        - [2, 1]
        - [1, 1]
    # pooling kernel size
    ks:
        - [2, 2]
        - [2, 2]
        - [2, 1]
        - [2, 1]
        - [1, 1]
    # dim of ouput feature map
    hidden: 256
